In [14]:
import numpy as np 
import pandas as pd # numpy wrapper 
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import yfinance as yf
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [15]:
# all the stocks that make up the snp500 index
tickers = ['AOS', 'ABT', 'ABBV', 'ABMD', 'ACN', 'ATVI', 'ADM', 'ADBE', 'ADP', 'AAP', 'AES', 'AFL', 'A', 'AIG', 'APD', 'AKAM', 'ALK', 'ALB', 'ARE', 'ALGN', 'ALLE', 'LNT', 'ALL', 'GOOGL', 'GOOG', 'MO', 'AMZN', 'AMCR', 'AMD', 'AEE', 'AAL', 'AEP',
              'AXP', 'AMT', 'AWK', 'AMP', 'ABC', 'AME', 'AMGN', 'APH', 'ADI', 'ANSS', 'ANTM', 'AON', 'APA', 'AAPL', 'AMAT', 'APTV', 'ANET', 'AIZ', 'T', 'ATO', 'ADSK', 'AZO', 'AVB', 'AVY', 'BKR', 'BLL', 'BAC', 'BBWI', 'BAX', 'BDX', 'WRB', 'BRK-A', 
              'BBY', 'BIO', 'TECH', 'BIIB', 'BLK', 'BK', 'BA', 'BKNG', 'BWA', 'BXP', 'BSX', 'BMY', 'AVGO', 'BR', 'BRO', 'BF-B', 'CHRW', 'CDNS', 'CZR', 'CPB', 'COF', 'CAH', 'KMX', 'CCL', 'CARR', 'CTLT', 'CAT', 'CBOE', 'CBRE', 'CDW', 'CE', 'CNC', 
              'CNP', 'CDAY', 'CERN', 'CF', 'CRL', 'SCHW', 'CHTR', 'CVX', 'CMG', 'CB', 'CHD', 'CI', 'CINF', 'CTAS', 'CSCO', 'C', 'CFG', 'CTXS', 'CLX', 'CME', 'CMS', 'KO', 'CTSH', 'CL', 'CMCSA', 'CMA', 'CAG', 'COP', 'ED', 'STZ', 'CEG', 'COO', 'CPRT', 
              'GLW', 'CTVA', 'COST', 'CTRA', 'CCI', 'CSX', 'CMI', 'CVS', 'DHI', 'DHR', 'DRI', 'DVA', 'DE', 'DAL', 'XRAY', 'DVN', 'DXCM', 'FANG', 'DLR', 'DFS', 'DISCA', 'DISCK', 'DISH', 'DIS', 'DG', 'DLTR', 'D', 'DPZ', 'DOV', 'DOW', 'DTE', 'DUK', 
              'DRE', 'DD', 'DXC', 'EMN', 'ETN', 'EBAY', 'ECL', 'EIX', 'EW', 'EA', 'EMR', 'ENPH', 'ETR', 'EOG', 'EPAM', 'EFX', 'EQIX', 'EQR', 'ESS', 'EL', 'ETSY', 'RE', 'EVRG', 'ES', 'EXC', 'EXPE', 'EXPD', 'EXR', 'XOM', 'FFIV', 'FDS', 'FAST', 'FRT', 
              'FDX', 'FITB', 'FRC', 'FE', 'FIS', 'FISV', 'FLT', 'FMC', 'F', 'FTNT', 'FTV', 'FBHS', 'FOXA', 'FOX', 'BEN', 'FCX', 'AJG', 'GRMN', 'IT', 'GE', 'GNRC', 'GD', 'GIS', 'GPC', 'GILD', 'GL', 'GPN', 'GM', 'GS', 'GWW', 'HAL', 'HIG', 'HAS', 'HCA', 
              'PEAK', 'HSIC', 'HSY', 'HES', 'HPE', 'HLT', 'HOLX', 'HD', 'HON', 'HRL', 'HST', 'HWM', 'HPQ', 'HUM', 'HII', 'HBAN', 'IEX', 'IDXX', 'ITW', 'ILMN', 'INCY', 'IR', 'INTC', 'ICE', 'IBM', 'IP', 'IPG', 'IFF', 'INTU', 'ISRG', 'IVZ', 'IPGP', 
              'IQV', 'IRM', 'JBHT', 'JKHY', 'J', 'JNJ', 'JCI', 'JPM', 'JNPR', 'K', 'KEY', 'KEYS', 'KMB', 'KIM', 'KMI', 'KLAC', 'KHC', 'KR', 'LHX', 'LH', 'LRCX', 'LW', 'LVS', 'LDOS', 'LEN', 'LLY', 'LNC', 'LIN', 'LYV', 'LKQ', 'LMT', 'L', 'LOW', 'LUMN',
              'LYB', 'MTB', 'MRO', 'MPC', 'MKTX', 'MAR', 'MMC', 'MLM', 'MAS', 'MA', 'MTCH', 'MKC', 'MCD', 'MCK', 'MDT', 'MRK', 'FB', 'MET', 'MTD', 'MGM', 'MCHP', 'MU', 'MSFT', 'MAA', 'MRNA', 'MHK', 'MOH', 'TAP', 'MDLZ', 'MPWR', 'MMM', 'MNST', 'MCO', 
              'MS', 'MOS', 'MSI', 'MSCI', 'NDAQ', 'NTAP', 'NFLX', 'NWL', 'NEM', 'NWSA', 'NWS', 'NEE', 'NLSN', 'NKE', 'NI', 'NDSN', 'NSC', 'NTRS', 'NOC', 'NLOK', 'NCLH', 'NRG', 'NUE', 'NVDA', 'NVR', 'NXPI', 'ORLY', 'OXY', 'ODFL', 'OMC', 'OKE', 'ORCL', 
              'OGN', 'OTIS', 'PCAR', 'PKG', 'PARA', 'PH', 'PAYX', 'PAYC', 'PYPL', 'PENN', 'PNR', 'PBCT', 'PEP', 'PKI', 'PFE', 'PM', 'PSX', 'PNW', 'PXD', 'PNC', 'POOL', 'PPG', 'PPL', 'PFG', 'PG', 'PGR', 'PLD', 'PRU', 'PEG', 'PTC', 'PSA', 'PHM', 'PVH', 
              'QRVO', 'PWR', 'QCOM', 'DGX', 'RL', 'RJF', 'RTX', 'O', 'REG', 'REGN', 'RF', 'RSG', 'RMD', 'RHI', 'ROK', 'ROL', 'ROP', 'ROST', 'RCL', 'SPGI', 'CRM', 'SBAC', 'SLB', 'STX', 'SEE', 'SRE', 'NOW', 'SHW', 'SBNY', 'SPG', 'SWKS', 'SJM', 'SNA',
              'SEDG', 'SO', 'LUV', 'SWK', 'SBUX', 'STT', 'STE', 'SYK', 'SIVB', 'SYF', 'SNPS', 'SYY', 'TMUS', 'TROW', 'TTWO', 'TPR', 'TGT', 'TEL', 'TDY', 'TFX', 'TER', 'TSLA', 'TXN', 'TXT', 'TMO', 'TJX', 'TSCO', 'TT', 'TDG', 'TRV', 'TRMB', 'TFC', 'TWTR', 
              'TYL', 'TSN', 'USB', 'UDR', 'ULTA', 'UAA', 'UA', 'UNP', 'UAL', 'UNH', 'UPS', 'URI', 'UHS', 'VLO', 'VTR', 'VRSN', 'VRSK', 'VZ', 'VRTX', 'VFC', 'VTRS', 'V', 'VNO', 'VMC', 'WAB', 'WMT', 'WBA', 'WM', 'WAT', 'WEC', 'WFC', 'WELL', 'WST', 'WDC', 
              'WRK', 'WY', 'WHR', 'WMB', 'WTW', 'WYNN', 'XEL', 'XYL', 'YUM', 'ZBRA', 'ZBH', 'ZION', 'ZTS']

In [18]:
# stocks_histories = yf.download(tickers, period="5y", auto_adjust=True, group_by='ticker')
stocks_histories = yf.download(tickers, period="5y", auto_adjust=False)['Adj Close']
stocks_histories

[*********************100%***********************]  505 of 505 completed

33 Failed downloads:
['MRO', 'BLL', 'PKI', 'DRE', 'DISCA', 'FBHS', 'CDAY', 'FLT', 'TWTR', 'FRC', 'WRK', 'DFS', 'RE', 'PBCT', 'ANSS', 'HES', 'SIVB', 'WBA', 'JNPR', 'DISH', 'PXD', 'CTLT', 'CTXS', 'ANTM', 'DISCK', 'NLSN', 'NLOK', 'PEAK', 'ABC', 'ABMD', 'CERN', 'PARA', 'ATVI']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

Ticker,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,...,WYNN,XEL,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2020-11-16,106.586227,12.790,134.800140,117.106323,80.938431,NaN,NaN,103.853508,227.996964,460.950012,...,92.277290,63.817894,31.461351,45.052086,92.143677,95.461876,140.146240,345.980011,33.802551,158.025879
2020-11-17,106.189919,12.700,133.229614,116.220467,81.637856,NaN,NaN,103.296188,226.945221,467.950012,...,91.780548,62.041145,31.881823,44.344746,90.781242,94.805786,140.080948,340.790009,33.674995,158.159744
2020-11-18,102.410545,12.740,132.158752,114.896568,81.234634,NaN,NaN,100.290306,223.138260,459.470001,...,93.153900,60.221676,30.678116,44.353809,89.863495,94.924217,138.252365,337.579987,33.113750,156.314606
2020-11-19,105.049355,12.790,130.356186,115.490387,82.016388,NaN,NaN,101.414093,226.368088,466.410004,...,96.183052,59.239346,30.834757,44.317532,89.286369,95.926605,136.703690,358.390015,32.646042,159.001083
2020-11-20,107.185524,12.530,128.794495,114.224892,82.979134,NaN,NaN,101.313568,226.591507,462.920013,...,92.812996,59.205166,30.455503,44.798168,89.295830,95.671471,136.153290,354.989990,32.552498,158.895920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-11-10,146.360001,13.310,47.549999,269.429993,218.710007,NaN,NaN,125.889999,244.550003,328.850006,...,128.880005,80.400002,118.220001,11.000000,151.050003,148.259995,88.730003,260.630005,52.610001,119.790001
2025-11-11,149.419998,12.990,51.060001,275.250000,225.169998,NaN,NaN,127.000000,242.559998,333.220001,...,126.070000,81.160004,119.779999,10.980000,149.779999,150.750000,88.500000,255.169998,52.669998,120.120003
2025-11-12,151.520004,13.460,51.020000,273.470001,233.229996,NaN,NaN,128.820007,246.529999,337.049988,...,125.019997,80.720001,118.120003,10.840000,149.869995,149.369995,90.029999,255.690002,52.450001,121.250000
2025-11-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-11-14,147.039993,12.945,49.880001,274.554993,232.945007,NaN,NaN,129.744995,247.919998,331.984985,...,122.570000,80.279999,118.620003,10.600000,145.699997,149.033798,89.669998,243.009995,50.810001,121.339996

In [ ]:
# calculate the daily returns 
daily_returns = stocks_histories.pct_change(fill_method=None)

# calculate the anunual means
annual_means_returns = daily_returns.mean() * 252 # 252 trading days in a year

# calculate annual returns variance 
annual_returs_variance = daily_returns.var() * 252

In [ ]:
stocks = list(stocks_histories.columns)
df2 = pd.DataFrame({'Stock Symbols': tickers})

# remove the date column - create columns for stock symbols and their variances 
df2['Variances'] = annual_returs_variance.values
df2['Returns'] = annual_means_returns.values

# show the data 
df2

    Stock Symbols  Variances   Returns
0               A   0.080860  0.111113
1             AAL   0.237193  0.127850
2             AAP   0.257851 -0.069906
3            AAPL   0.079169  0.209987
4            ABBV   0.050239  0.238315
..            ...        ...       ...
500           YUM   0.040468  0.110242
501           ZBH   0.067446 -0.054870
502          ZBRA   0.152554  0.016320
503          ZION   0.189976  0.184408
504           ZTS   0.069537 -0.018211

[505 rows x 3 columns]